name: Build-Test-Release (Mock)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Project
        run: |
          echo "Simulating build process..."
          mkdir dist
          echo "Build complete!" > dist/result.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Run Automated Tests
        run: |
          echo "Running mock tests..." 
          echo "All tests passed!"

  release:
    runs-on: ubuntu-latest
    needs: test
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist
      - name: Release Dev Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deploying dev release..."
          ls dist
          gh release create "dev-$(date +%s)" dist/* --notes "Automated mock release after successful tests"
