name: Build-Test-Release (Mock)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Project
        run: |
          echo "Simulating build process..."
          mkdir dist
          echo "Build complete!" > dist/result.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  test-unit:
    runs-on: ubuntu-latest
    needs: build
    env:
      TEST_ENV: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Run Unit Tests
        run: |
          echo "Running Unit Tests in $TEST_ENV environment..."
          echo "All unit tests passed!"

  test-integration:
    runs-on: ubuntu-latest
    needs: test-unit
    env:
      TEST_ENV: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Run Integration Tests
        run: |
          echo "Running Integration Tests in $TEST_ENV environment..."
          echo "All integration tests passed!"

  deploy-staging:
    needs: test-integration
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to Staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deploying to staging environment..."
          gh release create "staging-$(date +%s)" dist/* --notes "Testing pre-production release"

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to Production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deploying to production environment..."
          gh release create "prod-$(date +%s)" dist/* --notes "Production release after staging approval"
