name: Build-Test-Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Project
        run: |
          echo "Building project..."
          npm install
          npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Run Automated Tests
        run: |
          echo "Running automated tests..."
          npm test || (echo "Tests failed" && exit 1)

  release:
    runs-on: ubuntu-latest
    needs: test
    environment: dev
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Release Dev Build
        env:
          GITHUB_TOKEN: ${{ secrets.PATOKEN }}
        run: |
          echo "✅ Tests passed. Releasing new dev build..."
          gh release create "dev-$(date +%s)" dist/* --notes "Automated release after successful tests"
